### ISSUE TITLE
Solar Monitor

### ISSUE THREAD

**Issue by gokulshriyam** [robwestbrook/SolarPowerMonitor#1]
Hello,

I'm new to solar monitoring. But i wanted to build a solar monitor project as part of my graduation project.

You have mentioned that you have 245watts of solar panel.

So if the watts increases, does the hardware & software changes ??

regards

**Comment by robwestbrook** [comment]
My charge controller is good up to 20 amps in and out. More or less 400 watts.

**Comment by gokulshriyam** [comment]
Fine
thanks for the reply.

i'm closing this issue
